# Site settings
name: Gilberto A Garcia Jr
email: gilbertoagarciajr@gmail.com
keywords: "Software Engineer, Python, SQL, Agile"
skills: "Software Engineer in Chicago, IL"
baseurl: https://CaptainOmNoms.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/garcia-gilberto/
  - title: github
    url: https://github.com/CaptainOmNoms

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CDCDCD
  primary-rgb: "205, 205, 205"
  secondary: 88BBD6
  secondary-dark: 99D3DF
  section-tout: 88BBD6 



# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-hacker
