# Site settings
name: Gilberto A Garcia Jr
email: gilbertoagarciajr@gmail.com
keywords: "Software Engineer, Python, SQL, Agile"
skills: "Software Engineer in Chicago, IL"
baseurl: https://CaptainOmNoms.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/garcia-gilberto/
  - title: github
    url: https://github.com/CaptainOmNoms

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ADADAD
  primary-rgb: "173, 173, 173"
  secondary: 88BBD6
  secondary-dark: 666666
  section-tout: ADADAD 



# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-hacker
